# Generated by Django 5.1.1 on 2024-10-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_remove_product_promotion_delete_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(default="-", max_length=128),
            preserve_default=False,
        ),
    ]
