# Generated by Django 5.1.2 on 2024-10-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("store", "0004_customer_groups_customer_is_active_customer_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="customers", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="customers", to="auth.permission"
            ),
        ),
    ]
